- name: copy poetry env dir to node
  copy:
    src: ../files/
    dest: /home/{{ ansible_user }}/ray_worker/

- name: Fix ownership of poetry project directory
  become: true
  file:
    path: /home/ubuntu/ray_worker
    owner: ubuntu
    group: ubuntu
    recurse: yes