- name: Start Ray on worker nodes
  hosts: ray_worker_nodes
  become: true
  tasks:
    - name: Start Ray worker
      import_role:
        name: ray
        tasks_from: start_ray_on_worker_nodes.yaml