- name: scp configuration
  hosts: ray_worker_nodes
  become: true

  tasks:
    - name: Ensure sftp Subsystem is correctly set
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Subsystem\s+sftp'
        line: 'Subsystem sftp /usr/lib/openssh/sftp-server'
        state: present

    - name: Restart SSH to apply sftp config fix
      systemd_service:
        name: ssh
        state: restarted

- name: install Poetry
  hosts: ray_worker_nodes
  become: true

  tasks:
    - name: install poetry via apt
      apt:
        name: python3-poetry
        state: present
      
- name: initialize Poetry environment with Ray
  hosts: ray_worker_nodes
  become: true

  tasks:
    - name: copy poetry env dir to node
      copy:
        src: ../ray_env/
        dest: /home/{{ ansible_user }}/ray_worker/

    - name: Make all *.sh files in ray_worker executable
      shell: |
        chmod +x /home/{{ ansible_user }}/ray_worker/*.sh
      args:
        executable: /bin/bash

    - name: Install Poetry dependencies with PATH fix
      shell: |
        cd /home/ubuntu/ray_worker && /usr/bin/poetry update
      args:
        executable: /bin/bash

    - name: enable ray-worker service unit
      systemd_service:
        name: /home/{{ ansible_user }}/ray_worker/ray-worker.service
        enabled: true
    
    - name: Start ray-worker service
      systemd_service:
        state: started
        name: ray-worker.service

